### ISSUE TITLE
bspwm does not work with slim if there are multiple WMs

### ISSUE THREAD

**Issue by ghost** [windelicato/dotfiles#1]
BSPWM does not work with slim if you have your xinitrc set to "exec $1" which is necessary (according to the arch wiki) in order to use slim with multiple window managers.

Essentially, if you choose bspwm in slim and have another window manager, it won't work.
If the bspwm.desktop says to exec bspwm, slim freezes, and if it says to exec xinitrc, slim restarts.

Here is a reddit thread that has some of my configuration files as well as some of the things I've tried:
http://www.reddit.com/r/linuxquestions/comments/1rqro1/want_to_use_slim_and_multiple_environments/

**Comment by windelicato** [comment]
My bspwm.desktop calls this script, and it works fine for me.

https://github.com/windelicato/dotfiles/blob/master/scripts/wm

**Comment by ghost** [comment]
I embarassingly must ask what I did wrong.

I created a file and threw that script in it, made the file executable, then make bspwm.desktop exec to the absolute path of that file. When I used Slim to try to log onto bspwm, slim just froze.

**Comment by windelicato** [comment]
What version of slim do you have installed?

**Comment by ghost** [comment]
slim 1.3.6-2

**Comment by kevinvdburgt** [comment]
Arch have some issues with SLiM and systemd, see: https://wiki.archlinux.org/index.php/SLiM

**Comment by windelicato** [comment]
Weird. I did a `pacman -Syu` and have no problems with Slim 1.3.6 and FVWM, Openbox, BSPWM, and XMonad sessions coexisting. Does it work fine with a normal `~/.xinitrc` and `startx`?

**Comment by ghost** [comment]
It does, I'll take a look into some of my configuration files for something weird.
http://imgur.com/REy8riD
