### ISSUE TITLE
Panel Doesn't Show

### ISSUE THREAD

**Issue by thekingsleyr** [windelicato/dotfiles#2]
I don't have an irc client set up yet so I thought I would try and contact you here.

I followed your tutorial on how to set up bspwm and it works fine but I can't seem to get the panel to display. It seems it piped correctly, when I "echo $PANEL_FIFO" I get a answer of "/tmp/panel-fifo". I copied the two files, panel and panel_bar, from the examples folder of bspwm into my created folder ~/.config/panel and added the folder to my PATH. When I "echo $PATH" it returns with "/home/darkhorse/.config/panel" pasted onto the end. And when I cd into the panel directory, ~/.config/panel, and initiate "panel" it says "The panel is already running." but I get no display of a panel. I have LemonBoys Bar installed as well. I don't know what I am doing wrong...

**Comment by windelicato** [comment]
Do you have the font bar uses installed? I think its terminus by default

`ps aux | grep panel`
`pkill panel`
`~/.config/panel/panel`

**Comment by thekingsleyr** [comment]
I could have sworn I had terminus. I installed it but I am still getting now visual output of the bar. Interestingly enough when I run "~/.config/panel/panel" if responds with "Could not load font -_-terminus-medium-r-normal-_-12-_-_-_-c-_-*-1
" even though I can set my terminal font to terminus and it renders with no issues.

**Comment by windelicato** [comment]
xset +fp /path/to/terminus/font
xset fp rehash

Run something like that and add it to your login script

**Comment by thekingsleyr** [comment]
Bingo. Thank you very much. :smile:
