### ISSUE TITLE
Icons in bspwm panel

### ISSUE THREAD

**Issue by jfl209** [windelicato/dotfiles#5]
I get []'s instead of icons in my bspwm panel.  I'm guessing I'm using the wrong font?

**Comment by windelicato** [comment]
I updated the panel configs for you and added the missing bar config

see b8ae42602fd9025f54934140ce74eb91913a62d3

**Comment by jfl209** [comment]
Thanks. FWIW, I was using the wrong bar (should've picked up on that since I had to change to bar-aint-recursive).
