### ISSUE TITLE
Alpha Channel

### ISSUE THREAD

**Issue by ghost** [windelicato/dotfiles#6]
Hi. When using a compositor and following your tutorial https://github.com/windelicato/dotfiles/wiki/bspwm-for-dummies you will end up with an invisible bar. After many hours (I'm stupid) I found that the reason for this is because panel_colors lists colors in the rrggbb format and the current version of bar expects them to be in aarrggbb format when using a compositor. Without the alpha channel information you end up not being able to see bar at all.

bar manual states that if not using a compositor then the alpha channel will be silently ignored. Perhaps then it would be advantageous to alter panel_colors to include alpha channel in the colors or to modify panel. Or maybe make mention of this in your guide so users can do it themselves.

I realize that you have a disclaimer in your guide for just this type of issue occurring but for a new user like myself I literally spent hours puzzling out why I couldn't see bar!

**Comment by matchew** [comment]
I submitted a pull request to bspwm altering the panel_colors file. Hopefully this might solve the trouble with this guide, as I ended up with the same problem yesterday..._looks at name_...as I mentioned on bbs.archlinux yesterday you helped me solve my problem--thanks.

**Comment by ghost** [comment]
Ah great. I wasn't sure enough of myself to do something like that, but I'm glad someone else did!
