### ISSUE TITLE
Window Overlays Panel

### ISSUE THREAD

**Issue by Arucarn** [windelicato/dotfiles#7]
I've done everything in the instructions however when I open a window it overlays on top of the panel. I can't figure out how to change this. What do I need to do?

![screenshot](https://cloud.githubusercontent.com/assets/4622126/6259047/4106ce1c-b7c6-11e4-80da-97bc03964f42.png)

**Comment by kevinvdburgt** [comment]
You probably need to set the `bspc config top_padding 18` :-)

(18 is in pixels)

**Comment by Arucarn** [comment]
Thanks :) That fixed it.
