### ISSUE TITLE
can't start panel please help

### ISSUE THREAD

**Issue by Mattery** [windelicato/dotfiles#9]
i can't start the panel because of this:
[mattery@botnet ~]$ panel
/usr/bin/bar: Error: Unrecognized option: -g

Any idea of how can i fix this?

**Comment by kevinvdburgt** [comment]
You probably havent installed the correct 'bar' application. Are you sure you installed this one: https://github.com/LemonBoy/bar

What is the output op bar --version ?

**Comment by Mattery** [comment]
[mattery@botnet ~]$ bar --version
/usr/bin/bar: Error: Unrecognized option: --version

**Comment by Mattery** [comment]
[mattery@botnet ~]$ bar --version
/usr/bin/bar: Error: Unrecognized option: --version
Again unrecognized option, then i tried:
[mattery@botnet ~]$ bar -V
bar v1.4
And it outputs the version number

**Comment by kevinvdburgt** [comment]
Try `bar --help`

**Comment by samuelecioni** [comment]
I think that the problems are these:
- u have the wrong bar installed;
- install LemonBoy/bar as already said by @kevinvdburgt 
- change all the occurrency of `bar` with `lemonbar` (since the syntax seems to be changed) in .config/bspwm/panel/notify and .config/bspwm/panel/panel

**Comment by urumchi** [comment]
why don't you write clear that the bar is not other bar and it's lemonbar ?
